# Generated by Django 2.2.6 on 2020-01-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Empid',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(null='True'),
            preserve_default='True',
        ),
    ]
