# Generated by Django 3.0.2 on 2020-01-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20200115_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Empid',
            new_name='empid',
        ),
    ]
