# Generated by Django 3.0.2 on 2020-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200128_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='parmanent_address',
        ),
        migrations.AddField(
            model_name='profile',
            name='aadhaar',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(max_length=10, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='citizenship',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=256, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='father_dob',
            field=models.IntegerField(blank=True, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='father_firstname',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='father_lastname',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='father_nationality',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='name_as_per_aadhaar',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='pan_number',
            field=models.CharField(max_length=50, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_details',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='profile',
            name='temporary_address',
            field=models.CharField(max_length=500, null='True'),
            preserve_default='True',
        ),
    ]
