# Generated by Django 3.0.2 on 2020-01-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_auto_20200128_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='father_nationality',
            new_name='mother_lastname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='father_dob',
        ),
    ]
