# Generated by Django 3.0.2 on 2020-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20200128_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mother_firstname',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
