# Generated by Django 3.0.2 on 2020-01-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_profile_mother_firstname'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100, null='True'),
            preserve_default='True',
        ),
    ]
