# Generated by Django 2.2.6 on 2020-01-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea', models.TextField()),
                ('save_time', models.TextField()),
                ('save_money', models.TextField()),
                ('save_effort', models.TextField()),
            ],
        ),
    ]
