# Generated by Django 2.2.6 on 2020-01-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Banglore', max_length=256),
        ),
    ]
