# Generated by Django 3.0.2 on 2020-01-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_profile_full_name'),
        ('career', '0005_auto_20200116_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApply',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='employee.Profile')),
                ('phone', models.IntegerField()),
                ('upload_file', models.FileField(upload_to='resume/pdfs')),
            ],
            bases=('employee.profile',),
        ),
    ]
