# Generated by Django 3.0.2 on 2020-02-03 15:14

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0007_auto_20200129_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapply',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='jobapply',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='jobapply',
            name='profile_ptr',
        ),
        migrations.AddField(
            model_name='jobapply',
            name='full_name',
            field=models.EmailField(max_length=254, null='True'),
            preserve_default='True',
        ),
    ]
